# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cjoanne <cjoanne@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/04/21 12:30:03 by cjoanne           #+#    #+#              #
#    Updated: 2021/04/25 04:05:31 by cjoanne          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

SRCS =		ft_isdigit.c		ft_memccpy.c		ft_memcmp.c\
			ft_memcpy.c			ft_memset.c			ft_putchar_fd.c\
			ft_memchr.c			ft_bzero.c			ft_atoi.c\
			ft_isalpha.c		ft_memmove.c		ft_putstr_fd.c\
			ft_strmapi.c		ft_strlen.c			ft_strncmp.c\
			ft_tolower.c		ft_toupper.c		ft_isalnum.c\
			ft_putendl_fd.c		ft_isprint.c		ft_itoa.c\
			ft_putnbr_fd.c		ft_strchr.c			ft_strdup.c\
			ft_strlcat.c		ft_strlcpy.c		ft_strrchr.c\
			ft_strnstr.c		ft_isascii.c		ft_strjoin.c\
			ft_calloc.c			ft_substr.c			ft_strtrim.c\
			ft_split.c			ft_strcmp.c\
			ft_lstnew.c			ft_lstdelone.c		ft_lstadd_front.c\
			ft_lstsize.c		ft_lstlast.c		ft_lstadd_back.c\
			ft_lstclear.c		ft_lstmap.c			ft_lstiter.c

OBJS = $(patsubst %.c,%.o,$(SRCS))

FLAGS = -Wall -Wextra -Werror 

all : $(NAME)

$(NAME) : $(OBJS)
	@ar rcs $(NAME) $?

%.o : %.c
	@gcc $(FLAGS) -c $< -o $@

clean :
	@rm -f $(OBJS) $(OBJS_B)

fclean : clean
	@rm -f $(NAME)

re : fclean all

.PHONY : all clean fclean re bonus